### ISSUE TITLE
When type 'nile compile', got the error.

### ISSUE THREAD

**Issue by howardpen9** [martriay/nile#22]
![image](https://user-images.githubusercontent.com/36764495/137592001-8af117e8-2d8d-44c3-b500-d00da7e26aec.png)

As you can see, when I try to compile the cairo file, it show with these error. I tried to search on Google but can't find with any ideas. I think it's out of my knowledge, anyone know how to solve this? Thank you.

**Comment by martriay** [comment]
Could you provide some cose to reproduce the issue?

**Comment by martriay** [comment]
This seems to be an issue with the Cairo programming language on apple's M1 computers. I read on the Cairo discord that you were able to solve it. Leaving a few success stories taken from the [Cairo discord server](https://discord.gg/uJ9HZTUk2Y) for anybody stumbling upon this very problem:

### 1. @guiltygyoza

> Replying to myself for a working solution for M1-chip machine, the key to which is to install the x86 homebrew and use that to install & link gmp
> 1. Duplicate the terminal app and name it something else e.g. terminal_rosetta; set it to Open using Rosetta . Reference: https://medium.com/swlh/run-x86-terminal-apps-like-homebrew-on-your-new-m1-mac-73bdc9b0f343
> 2. In terminal_rosetta, open a virtual environment running python 3.7
> 3. Install the x86 homebrew by running arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" . It will get installed in /usr/local/
> 4. Use the x86 brew to install gmp by running /usr/local/bin/brew install gmp
> 5. Use the x86 brew to link gmp by running /usr/local/bin/brew link gmp
> 6. Follow the rest of the quickstart tutorial at https://www.cairo-lang.org/docs/quickstart.html


### 2. @milancermak 
> in case anyone else runs into this error fatal error: 'gmp.h' file not found when installing the necessary Cairo packages on a M1 Mac, after brew install gmp, try this:
```CFLAGS=-I/opt/homebrew/opt/gmp/include LDFLAGS=-L/opt/homebrew/opt/gmp/lib pip install ecdsa fastecdsa sympy```

### 3. @howardpen9 
> The python library fastecdsa has the issued in new MacOS or M1 chips I think!! You can't install the latest version. I reinstall the each version until the  fastecdsa==1.7.5 to run the code successfully! Finally!

### 4. myself!
None of the above worked for me :(
So I ended up spinning up a docker instance with ubuntu and installed Cairo in it.

**Comment by milancermak** [comment]
To make mine more generic, try:
```
CFLAGS=-I`brew --prefix gmp`/include LDFLAGS=-L`brew --prefix gmp`/lib pip install ecdsa fastecdsa sympy
```

**Comment by martriay** [comment]
Edited!

**Comment by 0xs34n** [comment]
I would suggest pinning this issue @martriay

**Comment by martriay** [comment]
Done

**Comment by machard** [comment]
@milancermak trick fixed it for me.
probably worth editing https://www.cairo-lang.org/docs/quickstart.html#quickstart

**Comment by ccarnino** [comment]
I tried the @milancermak solution, but on my macOS BigSur on M1, `pip` is not found, while `pip3` is.
So modifying Milan's command to the following, I was then able to `pip3 install cairo-lang` successfully.

```
CFLAGS=-I`brew --prefix gmp`/include LDFLAGS=-L`brew --prefix gmp`/lib pip3 install ecdsa fastecdsa sympy
```

**Comment by QEDK** [comment]
> To make mine more generic, try:
> 
> ```
> CFLAGS=-I`brew --prefix gmp`/include LDFLAGS=-L`brew --prefix gmp`/lib pip install ecdsa fastecdsa sympy
> ```

Worked for me! Appreciate it.

**Comment by kootsZhin** [comment]
I noticed that you are using ```python3.8```, try setting up your virtual env in ```python3.7```, I am using macOS Monterey (12.2) on M1 Pro and everything works perfectly while I'm using ```python3.7``` as stated in the Cairo lang doc [here](https://www.cairo-lang.org/docs/quickstart.html).

**Comment by benminer** [comment]
Option 1 worked for me, thank you!

**Comment by daramir** [comment]
Got it to work using:
- Pipenv (my preference) but normal `venv` should be fine
- MacOS's Python 3.8
- @milancermak 's [Point 2](https://github.com/OpenZeppelin/nile/issues/22#issuecomment-945179452)
- @howardpen9 's fastecdsa==1.7.5

**Comment by chee-chyuan** [comment]
> fastecdsa==1.7.5

this works for me. thank you so much

**Comment by chee-chyuan** [comment]
some kind soul posted this and it works for me https://th0rgal.medium.com/the-easiest-way-to-setup-a-cairo-dev-environment-8f2a63610d46

**Comment by zinderud** [comment]
> CFLAGS=-I`brew --prefix gmp`/include LDFLAGS=-L`brew --prefix gmp`/lib pip3 install ecdsa fastecdsa sympy


Thanks, I've been trying to figure this out for days. This time it happened

**Comment by clement-ux** [comment]
> To make mine more generic, try:
> 
> ```
> CFLAGS=-I`brew --prefix gmp`/include LDFLAGS=-L`brew --prefix gmp`/lib pip install ecdsa fastecdsa sympy
> ```

I'm using M1 chip, this works for me, thanks!

**Comment by bleso-a** [comment]
I am also using M1 Chip, the command below also works for me

```
CFLAGS=-I`brew --prefix gmp`/include LDFLAGS=-L`brew --prefix gmp`/lib pip install ecdsa fastecdsa sympy
```

**Comment by emmaguo13** [comment]
compiling works for me, but not execution
getting the same error as this one here: https://github.com/AntonKueltz/fastecdsa/issues/74#issuecomment-979722516 
probably will just spin up a docker container, but would love to know if execution works for any of you

**Comment by ccsoloist** [comment]
> I tried the @milancermak solution, but on my macOS Monterey (12.1) on M1, `pip` is not found, while `pip3` is. So modifying Milan's command to the following, I was then able to `pip3 install cairo-lang` successfully.
> 
> ```
> CFLAGS=-I`brew --prefix gmp`/include LDFLAGS=-L`brew --prefix gmp`/lib pip3 install ecdsa fastecdsa sympy
> ```

Thx! This worked for me! I ran this command after completely removing python on machine (reinstalling python3.9).

**Comment by Samk13** [comment]
To fix this error:
`OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': dlopen(libcairo.so.2, 0x0002): tried: 'libcairo.so.2' (no such file), '/usr/local/lib/libcairo.so.2' (no such file), '/usr/lib/libcairo.so.2' (no such file), '/Users/soma/Development/mkdocs-material-insiders/libcairo.so.2' (no such file), '/usr/local/lib/libcairo.so.2' (no such file), '/usr/lib/libcairo.so.2' (no such file)
cannot load library 'libcairo.2.dylib': dlopen(libcairo.2.dylib, 0x0002): tried: 'libcairo.2.dylib' (no such file), '/usr/local/lib/libcairo.2.dylib' (no such file), '/usr/lib/libcairo.2.dylib' (no such file), '/Users/soma/Development/mkdocs-material-insiders/libcairo.2.dylib' (no such file), '/usr/local/lib/libcairo.2.dylib' (no such file), '/usr/lib/libcairo.2.dylib' (no such file)
cannot load library 'libcairo-2.dll': dlopen(libcairo-2.dll, 0x0002): tried: 'libcairo-2.dll' (no such file), '/usr/local/lib/libcairo-2.dll' (no such file), '/usr/lib/libcairo-2.dll' (no such file), '/Users/soma/Development/mkdocs-material-insiders/libcairo-2.dll' (no such file), '/usr/local/lib/libcairo-2.dll' (no such file), '/usr/lib/libcairo-2.dll' (no such file)`

run this command:
`ln -s /opt/homebrew/lib/libcairo.2.dylib .`
